export const AgentCanvasABI = [
  {
    inputs: [
      { name: "_usdc", type: "address" },
      { name: "_treasury", type: "address" },
    ],
    stateMutability: "nonpayable",
    type: "constructor",
  },
  { inputs: [], name: "AlreadyOwned", type: "error" },
  { inputs: [], name: "InvalidPixelId", type: "error" },
  { inputs: [], name: "InvalidPrice", type: "error" },
  { inputs: [], name: "NotForSale", type: "error" },
  { inputs: [], name: "TransferFailed", type: "error" },
  { inputs: [], name: "Unauthorized", type: "error" },
  {
    anonymous: false,
    inputs: [
      { indexed: true, name: "owner", type: "address" },
      { indexed: false, name: "displayName", type: "string" },
      { indexed: false, name: "twitter", type: "string" },
      { indexed: false, name: "website", type: "string" },
      { indexed: false, name: "ca", type: "string" },
    ],
    name: "ProfileUpdated",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, name: "pixelId", type: "uint256" },
      { indexed: true, name: "buyer", type: "address" },
      { indexed: true, name: "previousOwner", type: "address" },
      { indexed: false, name: "pricePaid", type: "uint256" },
      { indexed: false, name: "fee", type: "uint256" },
    ],
    name: "PixelBought",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, name: "pixelId", type: "uint256" },
      { indexed: true, name: "owner", type: "address" },
      { indexed: false, name: "price", type: "uint256" },
    ],
    name: "PixelListed",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, name: "pixelId", type: "uint256" },
      { indexed: true, name: "owner", type: "address" },
    ],
    name: "PixelUnlisted",
    type: "event",
  },
  {
    inputs: [{ name: "wallet", type: "address" }],
    name: "getProfile",
    outputs: [
      { name: "", type: "string" },
      { name: "", type: "string" },
      { name: "", type: "string" },
      { name: "", type: "string" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ name: "id", type: "uint256" }],
    name: "getPixel",
    outputs: [
      { name: "owner", type: "address" },
      { name: "price", type: "uint256" },
      { name: "forSale", type: "bool" },
      { name: "exists", type: "bool" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ name: "id", type: "uint256" }],
    name: "buy",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { name: "id", type: "uint256" },
      { name: "price", type: "uint96" },
    ],
    name: "list",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ name: "id", type: "uint256" }],
    name: "unlist",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { name: "displayName", type: "string" },
      { name: "twitter", type: "string" },
      { name: "website", type: "string" },
      { name: "ca", type: "string" },
    ],
    name: "setProfile",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { name: "x", type: "uint256" },
      { name: "y", type: "uint256" },
    ],
    name: "pixelId",
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "pure",
    type: "function",
  },
  {
    inputs: [{ name: "id", type: "uint256" }],
    name: "pixels",
    outputs: [
      { name: "owner", type: "address" },
      { name: "price", type: "uint96" },
      { name: "exists", type: "bool" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "GRID_SIZE",
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "MAX_PIXELS",
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "treasury",
    outputs: [{ name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "USDC",
    outputs: [{ name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
] as const;
